name: Update Meta Alpha
on:
  workflow_dispatch:
  schedule:
    - cron: "30 16 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - ".github/workflows/delete-old-workflows.yml"
      - ".github/workflows/update-dae-prerelease.yml"
      - ".github/workflows/update-dae-release.yml"
      - ".github/workflows/update-meta-release.yml"
      - ".github/workflows/update-clashdashboard.yml"
      - ".github/workflows/update-mosdns-release.yml"

permissions: write-all

env:
  download_url: https://github.com/MetaCubeX/mihomo/releases/download
  download_version: ''

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@main

    - name: Download and unzip `upx`
      run: |
        mkdir -p ./tmp ./bin ./bin/Meta-alpha
        upx_version=$(curl -sSL https://api.github.com/repos/upx/upx/releases/latest | grep 'tag_name' | sed 's/.*v//g' | sed 's/",$//g')
        echo "upx_version=${upx_version}" >> ${GITHUB_ENV}
        wget -P ./tmp "https://github.com/upx/upx/releases/download/v${upx_version}/upx-${upx_version}-amd64_linux.tar.xz"
        tar -xf "./tmp/upx-${upx_version}-amd64_linux.tar.xz" -C ./tmp
        rm -f ./tmp/*.tar.xz

    - name: Download and compress `Meta core`
      run: |
        download_version=$(curl -sSL https://api.github.com/repos/MetaCubeX/mihomo/releases/tags/Prerelease-Alpha | grep 'linux-arm64' | head -n 1 | sed 's/.*\(alpha\)/\1/g' | sed 's/.gz.*//g')
        echo "download_version=${download_version}" >> ${GITHUB_ENV}
        archs=(amd64-compatible armv7 arm64)
        new_name=(amd64 armv7 arm64)
        for((i=0;i<3;i++)); do
          wget "${download_url}/Prerelease-Alpha/mihomo-linux-${archs[i]}-${download_version}.gz" -O - | gunzip -c > "./tmp/mihomo-linux-${new_name[i]}"
          chmod +x "./tmp/mihomo-linux-${new_name[i]}"
          "./tmp/upx-${upx_version}-amd64_linux/upx" "./tmp/mihomo-linux-${new_name[i]}"
          mv -f "./tmp/mihomo-linux-${new_name[i]}" "./tmp/meta-linux-${new_name[i]}"
        done
        rm -rf ./tmp/upx*

    - name: Move `Meta core` to `Meta-alpha` directory
      run: |
        rm -rf ./bin/Meta-alpha/*
        cp -f ./tmp/* ./bin/Meta-alpha
        rm -rf ./tmp
        sed -i '/Meta-alpha_v*/'d ./bin/version
        echo Meta-alpha_v=${download_version} >> ./bin/version

    - name: Commit and push
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add . && git commit -m "更新 Meta 内核 Alpha 版至 ${download_version}" || exit 0
        git push -f

    - name: Purge jsDelivr CDN
      run: |
        cd ./bin/Meta-alpha || exit 1
        for file in $(ls); do
          curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@main/bin/Meta-alpha/${file}"
        done
